import { useTranslation } from "react-i18next";
import Link from "next/link";
import LanguageSelector from "components/LanguageSelector";
import Head from "next/head";
const About = () => {
  const { t } = useTranslation("about");

  return (
    <>
      <Head>
        <title>{t("title")}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <Link
          className="my-5 rounded bg-blue-500 px-4 py-2 font-bold text-white"
          href={"/"}
        >
          Home page
        </Link>
        <LanguageSelector />
        <div className="my-5 flex flex-col items-center justify-center">
          <h1 className="text-3xl font-bold text-gray-700">{t("title")}</h1>
          <h3 className="text-lg text-gray-700">{t("content")}</h3>
        </div>
      </main>
    </>
  );
};

export default About;
