import Head from "next/head";
import { GetServerSideProps } from "next";
import LanguageSelector from "components/LanguageSelector";
interface HomeProps {
  selectedLanguage: string;
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async (
  context,
) => {
  console.log("context.req.headers.cookie", context.req.headers.cookie);
  const selectedLanguage =
    context.req.headers.cookie
      ?.split("; ")
      .find((row) => row.startsWith("selectedLanguage="))
      ?.split("=")[1] ?? "en";

  return {
    props: {
      selectedLanguage,
    },
  };
};

const Home: React.FC<HomeProps> = ({ selectedLanguage }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div>
          <h1>Welcome to My Next.js App</h1>
          <LanguageSelector />
          <p>Content in {selectedLanguage}</p>
        </div>
      </main>
    </>
  );
};
export default Home;
